---
title: "STAT545 Homework 3"
author: "Frederike Basedow"
date: "26 September 2018"
output: github_document
---

1. Get the maximum and minimum of GDP per capita for all continents.

2. Look at the spread of GDP per capita within the continents.

3. Compute a trimmed mean of life expectancy for different years. Or a weighted mean, weighting by population. Just try something other than the plain vanilla mean.

4. How is life expectancy changing over time on different continents?

5. Report the absolute and/or relative abundance of countries with low life expectancy over time by continent: Compute some measure of worldwide life expectancy – you decide – a mean or median or some other quantile or perhaps your current age. Then determine how many countries on each continent have a life expectancy less than this benchmark, for each year.

6. Find countries with interesting stories. Open-ended and, therefore, hard. Promising but unsuccessful attempts are encouraged. This will generate interesting questions to follow up on in class.

Or, make up your own! Between the dplyr coverage in class and the list above, I think you get the idea.